# Generated by Django 4.2.6 on 2023-10-14 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_latitude', models.FloatField(max_length=200)),
                ('destination_longitude', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=25)),
                ('created', models.DateField(auto_now_add=True)),
                ('eventDate', models.DateField()),
                ('users', models.ManyToManyField(default=None, related_name='workshopUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busno', models.IntegerField()),
                ('destination_name', models.CharField(max_length=60)),
                ('current_bus_driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.busdriver')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('inbetween_routes', models.ManyToManyField(related_name='inbetween_routes', to='api.location')),
            ],
        ),
    ]
