# Generated by Django 4.2.3 on 2023-07-27 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_post_alter_student_user_postslikes_postcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postType',
            field=models.CharField(choices=[('general', 'General'), ('achivements', 'Achivements'), ('workshop', 'Workshop'), ('events', 'Events')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('staff', 'Staff'), ('club', 'Club')], default='admin', max_length=8),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=5)),
                ('groups', models.ManyToManyField(blank=True, related_name='club_users', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='club_users_permissions', to='auth.permission')),
            ],
        ),
    ]
