# Generated by Django 4.2.3 on 2023-07-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_postimage_alter_post_posttype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='clubName',
            new_name='clubname',
        ),
    ]
