# Generated by Django 4.2.6 on 2023-10-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_busdriver_user_alter_busdriver_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='destination_latitude',
            new_name='location_latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='destination_longitude',
            new_name='location_longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(default='location', max_length=150),
        ),
    ]
