# Generated by Django 4.2.3 on 2023-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_clubname_club_clubname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='clubname',
            field=models.TextField(max_length=15),
        ),
    ]
