# Generated by Django 4.2.6 on 2023-12-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_destination_latitude_location_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
