# Generated by Django 4.2.3 on 2023-07-30 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_club_clubname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='postLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostsLikes',
        ),
    ]
