# Generated by Django 4.2.3 on 2023-07-30 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_likes_delete_postslikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='postLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
