# Generated by Django 4.2.6 on 2023-12-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlechatrooms',
            old_name='roomKey',
            new_name='room_key',
        ),
    ]
