# Generated by Django 4.2.6 on 2023-12-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_roomkey_singlechatrooms_room_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='msg',
            new_name='message',
        ),
    ]
